package com.jetslice.quotesparse;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.MotionEvent;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ProgressBar;
import android.widget.Spinner;
import android.widget.Toast;

import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.util.ArrayList;

public class MainActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener{
    RecyclerView recyclerView;
    private RecyclerAdapter adapter1;
    ProgressBar progressBar;
    public String url_argument = "https://api.jsonbin.io/b/5a1d7ef3b8da14396b8ff4bb";
    public String url_advice="https://api.jsonbin.io/b/5a39ffbef086f95991cdb706";
    public String url_actions = "https://api.jsonbin.io/b/5a39fc530032bb59bf719f9b";
    public String url_america="https://api.jsonbin.io/b/5a3a6cedf086f95991cdb72d";
    public String url_attitude="https://api.jsonbin.io/b/5a3a6ec6cbfe1e441c4074bf";
    public String url_authority="https://api.jsonbin.io/b/5a3a705394edf544445cc565";
    public String url_autmn="https://api.jsonbin.io/b/5a41ddb7163d58482c19d588";
    public String url_balance="https://api.jsonbin.io/b/5a41df95e01e8f485451c127";
    public String url_beauty="https://api.jsonbin.io/b/5a41e14d7835fe482d9cbf0d";
    public String url_belief="https://api.jsonbin.io/b/5a41e1f2664554485a29a19f";
    public String url_birds = "https://api.jsonbin.io/b/5a41e3a3163d58482c19d589";
    public String url_body = "https://api.jsonbin.io/b/5a41e48b664554485a29a1a0";
    public String url_books="https://api.jsonbin.io/b/5a41e690163d58482c19d58b";
    public String url_boredom = "https://api.jsonbin.io/b/5a41e777163d58482c19d58c";
    public String url_brain="https://api.jsonbin.io/b/5a41e93d7835fe482d9cbf11";
    public String url_business="https://api.jsonbin.io/b/5a41eeea664554485a29a1a6";
    public String url_camping="https://api.jsonbin.io/b/5a42408ce01e8f485451c133";
    public String url_cats="https://api.jsonbin.io/b/5a42420a7835fe482d9cbf17";
    public String url_chance="https://api.jsonbin.io/b/5a44c5a17835fe482d9cbfef";
    public String url_change="http://api.jsonbin.io/b/5a44c657e01e8f485451c20c";
    public String url_character="https://api.jsonbin.io/b/5a44c7cc664554485a29a298";
    public String url_christmas="https://api.jsonbin.io/b/5a44c7fae01e8f485451c20e";
    public String url_civilization="https://api.jsonbin.io/b/5a44cb017835fe482d9cbff0";
    public String url_cliche="https://api.jsonbin.io/b/5a44cb46664554485a29a299";
    public String url_commonsense = "https://api.jsonbin.io/b/5a44cc22664554485a29a29a";
    public String url_communication="https://api.jsonbin.io/b/5a46309c664554485a29a324";
    public String url_communism="https://api.jsonbin.io/b/5a46318be01e8f485451c284";
    public String url_community="https://api.jsonbin.io/b/5a4631fce01e8f485451c285";
    public String url_compete="https://api.jsonbin.io/b/5a4633887835fe482d9cc06e";
    public String url_computers="https://api.jsonbin.io/b/5a4634e17835fe482d9cc070";
    public String url_conceit="https://api.jsonbin.io/b/5a46379f7835fe482d9cc072";
    public String url_confidence="https://api.jsonbin.io/b/5a4638407835fe482d9cc074";
    public String url_conservative="https://api.jsonbin.io/b/5a467042664554485a29a33d";
    public String url_conversation="https://api.jsonbin.io/b/5a467266163d58482c19d702";
    public String url_courage="https://api.jsonbin.io/b/5a46754c7835fe482d9cc084";
    public String url_coward="https://api.jsonbin.io/b/5a467aab7835fe482d9cc088";
    public String url_creativity="https://api.jsonbin.io/b/5a4683e37835fe482d9cc08d";
    public String url_crime="https://api.jsonbin.io/b/5a4685567835fe482d9cc08e";
    public String url_criticism="https://api.jsonbin.io/b/5a46862d7835fe482d9cc08f";
    public String url_curiosity="https://api.jsonbin.io/b/5a472c8b7835fe482d9cc0cc";
    public String url_cynicism="https://api.jsonbin.io/b/5a472cf2664554485a29a37b";
    public String url_dance="https://api.jsonbin.io/b/5a472f83664554485a29a37e";
    public String url_death="https://api.jsonbin.io/b/5a47308f664554485a29a37f";
    public String url_decision="https://api.jsonbin.io/b/5a473152664554485a29a381";
    public String url_defeat="https://api.jsonbin.io/b/5a4731bd664554485a29a382";
    public String url_democracy="https://api.jsonbin.io/b/5a47414c664554485a29a389";
    public String url_design="https://api.jsonbin.io/b/5a474219664554485a29a38a";
    public String url_destiny="https://api.jsonbin.io/b/5a4744df664554485a29a38d";
    public String url_differences="https://api.jsonbin.io/b/5a47458a163d58482c19d755";
    public String url_dignity="https://api.jsonbin.io/b/5a474764664554485a29a38e";
    public String url_discovery="https://api.jsonbin.io/b/5a4747d7e01e8f485451c2e3";
    public String url_dogs="https://api.jsonbin.io/b/5a474847163d58482c19d756";
    public String url_doubt="https://api.jsonbin.io/b/5a4748b2163d58482c19d758";
    public String url_dream="https://api.jsonbin.io/b/5a474a7de01e8f485451c2e5";
    public String url_duty="https://api.jsonbin.io/b/5a474d56e01e8f485451c2e8";
    public String url_economics="https://api.jsonbin.io/b/5a475903664554485a29a394";
    public String url_education="https://api.jsonbin.io/b/5a4759e6664554485a29a395";
    public String url_enemies="https://api.jsonbin.io/b/5a475a5c664554485a29a397";
    public String url_energy="https://api.jsonbin.io/b/5a475ac97835fe482d9cc0da";
    public String url_england="https://api.jsonbin.io/b/5a475b64163d58482c19d75f";
    public String url_english="https://api.jsonbin.io/b/5a475cb7163d58482c19d761";
    public String url_environment="https://api.jsonbin.io/b/5a475d30664554485a29a399";
    public String url_equality="https://api.jsonbin.io/b/5a475de6e01e8f485451c2ef";
    public String url_etiquette="https://api.jsonbin.io/b/5a475e43163d58482c19d762";
    public String url_evil="https://api.jsonbin.io/b/5a475f31664554485a29a39b";
    public String url_excel="https://api.jsonbin.io/b/5a475ff97835fe482d9cc0db";
    public String url_exercise="https://api.jsonbin.io/b/5a4760ece01e8f485451c2f2";
    public String url_experience="https://api.jsonbin.io/b/5a476149664554485a29a39c";
    public String url_experts="https://api.jsonbin.io/b/5a47619a7835fe482d9cc0dd";
    public String url_exploration="https://api.jsonbin.io/b/5a4762e5163d58482c19d764";
    public String url_facts="https://api.jsonbin.io/b/5a477eed664554485a29a3a7";
    public String url_failure="https://api.jsonbin.io/b/5a477fa9163d58482c19d76e";
    public String url_faith="https://api.jsonbin.io/b/5a478080664554485a29a3aa";
    public String url_fame="https://api.jsonbin.io/b/5a4780fe7835fe482d9cc0e7";
    public String url_family="https://api.jsonbin.io/b/5a478166e01e8f485451c2fc";
    public String url_fashion="https://api.jsonbin.io/b/5a4781cfe01e8f485451c2fd";
    public String url_fate="https://api.jsonbin.io/b/5a47822e664554485a29a3ab";
    public String url_fear="https://api.jsonbin.io/b/5a4782c9664554485a29a3ac";
    public String url_flowers="https://api.jsonbin.io/b/5a4783c8664554485a29a3ae";
    public String url_food="https://api.jsonbin.io/b/5a478f537835fe482d9cc0eb";
    public String url_forgiveness="https://api.jsonbin.io/b/5a4790197835fe482d9cc0ec";
    public String url_fortune="https://api.jsonbin.io/b/5a4790d4163d58482c19d774";
    public String url_freedom="https://api.jsonbin.io/b/5a4791857835fe482d9cc0ed";
    public String url_friends="https://api.jsonbin.io/b/5a4793c2e01e8f485451c306";
    public String url_genius="https://api.jsonbin.io/b/5a479479e01e8f485451c307";
    public String url_giving="https://api.jsonbin.io/b/5a4794ed163d58482c19d777";
    public String url_goals="https://api.jsonbin.io/b/5a4795cf7835fe482d9cc0ef";
    public String url_god="https://api.jsonbin.io/b/5a47966de01e8f485451c309";
    public String url_golf="https://api.jsonbin.io/b/5a479741664554485a29a3b6";
    public String url_gossip="https://api.jsonbin.io/b/5a479800e01e8f485451c30b";
    public String url_government="https://api.jsonbin.io/b/5a479901163d58482c19d778";
    public String url_gratitude="https://api.jsonbin.io/b/5a479977e01e8f485451c30d";
    public String url_greatness="https://api.jsonbin.io/b/5a479a10e01e8f485451c30e";
    public String url_greed="https://api.jsonbin.io/b/5a479a7fe01e8f485451c30f";
    public String url_grief="https://api.jsonbin.io/b/5a479ae3163d58482c19d77a";
    public String url_guilt="https://api.jsonbin.io/b/5a47a2e0163d58482c19d77e";
    public String url_habits="https://api.jsonbin.io/b/5a47a4de7835fe482d9cc0f8";
    public String url_happiness="https://api.jsonbin.io/b/5a47a61e163d58482c19d781";
    public String url_hate="https://api.jsonbin.io/b/5a47a822e01e8f485451c314";
    public String url_hatred="https://api.jsonbin.io/b/5a47a8c3163d58482c19d783";
    public String url_health="https://api.jsonbin.io/b/5a47c8aa664554485a29a3ca";
    public String url_hero="https://api.jsonbin.io/b/5a47b65a664554485a29a3c2";
    public String url_history="https://api.jsonbin.io/b/5a47c729e01e8f485451c320";
    public String url_hollywood="https://api.jsonbin.io/b/5a47c920664554485a29a3cb";
    public String url_home="https://api.jsonbin.io/b/5a47c9a4163d58482c19d792";
    public String url_honesty="https://api.jsonbin.io/b/5a47ca967835fe482d9cc10c";
    public String url_honor="https://api.jsonbin.io/b/5a47cafd7835fe482d9cc10d";
    public String url_hope="https://api.jsonbin.io/b/5a47cb5b163d58482c19d795";
    public String url_humility="https://api.jsonbin.io/b/5a47cbc37835fe482d9cc10e";
    public String url_humour="https://api.jsonbin.io/b/5a47cc7d163d58482c19d796";
    public String url_idealism="https://api.jsonbin.io/b/5a47cd7ee01e8f485451c323";
    public String url_ideas="https://api.jsonbin.io/b/5a47ce2ae01e8f485451c324";
    public String url_ignorance="https:/api.jsonbin.io/b/5a47ce93664554485a29a3cd";
    public String url_imagination="https://api.jsonbin.io/b/5a47cee8163d58482c19d799";
    public String url_immoratality="https://api.jsonbin.io/b/5a47cf48163d58482c19d79a";
    public String url_inspiration="https://api.jsonbin.io/b/5a47cfa2163d58482c19d79b";
    public String url_instinct="https://api.jsonbin.io/b/5a47cffe7835fe482d9cc111";
    public String url_integrity="https://api.jsonbin.io/b/5a47d0647835fe482d9cc112";
    public String url_intelligence="https://api.jsonbin.io/b/5a47d1077835fe482d9cc114";
    public String url_internet="https://api.jsonbin.io/b/5a47d178163d58482c19d79c";
    public String url_invention="https://api.jsonbin.io/b/5a47d1d3e01e8f485451c325";
    public String url_jealousy="https://api.jsonbin.io/b/5a47d225163d58482c19d79e";
    public String url_journalism="https://api.jsonbin.io/b/5a47d2667835fe482d9cc115";
    public String url_joy="https://api.jsonbin.io/b/5a47d2f0664554485a29a3cf";
    public String url_justice="https://api.jsonbin.io/b/5a47d3f8e01e8f485451c327";
    public String url_kindness="https://api.jsonbin.io/b/5a47d45d163d58482c19d7a1";
    public String url_knowledge="https://api.jsonbin.io/b/5a47d4f6e01e8f485451c329";
    public String url_language="https://api.jsonbin.io/b/5a47d557664554485a29a3d3";
    public String url_laughter="https://api.jsonbin.io/b/5a47d5ac664554485a29a3d4";
    public String url_laws="https://api.jsonbin.io/b/5a47d602e01e8f485451c32a";
    public String url_laziness="https://api.jsonbin.io/b/5a47d656e01e8f485451c32b";
    public String url_leadership="https://api.jsonbin.io/b/5a47d69ae01e8f485451c32c";
    public String url_learning="https://api.jsonbin.io/b/5a47d717e01e8f485451c32d";
    public String url_legacy="https://api.jsonbin.io/b/5a47d833664554485a29a3d6";
    public String url_liberals="https://api.jsonbin.io/b/5a47d8717835fe482d9cc119";
    public String url_lies="https://api.jsonbin.io/b/5a47d8c3664554485a29a3d7";
    public String url_life="https://api.jsonbin.io/b/5a47d950163d58482c19d7a5";
    public String url_light="https://api.jsonbin.io/b/5a47d9e1163d58482c19d7a6";
    public String url_listening="https://api.jsonbin.io/b/5a47da3ae01e8f485451c330";
    public String url_lonliness="https://api.jsonbin.io/b/5a47da7ae01e8f485451c331";
    public String url_love="https://api.jsonbin.io/b/5a47dc02664554485a29a3da";
    public String url_luck="https://api.jsonbin.io/b/5a47dc57e01e8f485451c334";
    public String url_magic="https://api.jsonbin.io/b/5a47dcb6e01e8f485451c335";
    public String url_mankind="https://api.jsonbin.io/b/5a47dff77835fe482d9cc11d";
    public String url_marriage="https://api.jsonbin.io/b/5a47e10de01e8f485451c336";
    public String url_mathematics="https://api.jsonbin.io/b/5a47e16c163d58482c19d7ab";
    public String url_medicine="https://api.jsonbin.io/b/5a47e1c67835fe482d9cc11e";
    public String url_memory="https://api.jsonbin.io/b/5a47e225664554485a29a3de";
    public String url_menandwoman="https://api.jsonbin.io/b/5a47e3ade01e8f485451c339";
    public String url_mercy="https://api.jsonbin.io/b/5a485b72e01e8f485451c366";
    public String url_mistakes="https://api.jsonbin.io/b/5a485c08163d58482c19d7d3";
    public String url_money="https://api.jsonbin.io/b/5a485c56e01e8f485451c367";
    public String url_morality="htpps://api.jsonbin.io/b/5a485cc97835fe482d9cc14f";
    public String url_morning="https://api.jsonbin.io/b/5a485d15e01e8f485451c368";
    public String url_music="https://api.jsonbin.io/b/5a485da3664554485a29a408";
    public String url_nature="https://api.jsonbin.io/b/5a485e23664554485a29a409";
    public String url_necessity="https://api.jsonbin.io/b/5a485e80163d58482c19d7d4";
    public String url_night="https://api.jsonbin.io/b/5a485ec2664554485a29a40b";
    public String url_nobility="https://api.jsonbin.io/b/5a485ef9664554485a29a40c";
    public String url_opinions="https://api.jsonbin.io/b/5a485f5e664554485a29a40d";
    public String url_opportunity="https://api.jsonbin.io/b/5a485fade01e8f485451c36b";
    public String url_optimism="https://api.jsonbin.io/b/5a486004e01e8f485451c36c";
    public String url_painting="https://api.jsonbin.io/b/5a48603f163d58482c19d7d5";
    public String url_parents="https://api.jsonbin.io/b/5a486183163d58482c19d7d6";
    public String url_passion="https://api.jsonbin.io/b/5a486200e01e8f485451c36e";
    public String url_patience="https://api.jsonbin.io/b/5a486256e01e8f485451c36f";
    public String url_patiotism="https://api.jsonbin.io/b/5a4862cbe01e8f485451c370";
    public String url_peace="https://api.jsonbin.io/b/5a4863fd664554485a29a410";
    public String url_perfection="https://api.jsonbin.io/b/5a4864937835fe482d9cc152";
    public String url_preserverance="https://api.jsonbin.io/b/5a4864d9e01e8f485451c371";
    public String url_philosophy="https://api.jsonbin.io/b/5a48654be01e8f485451c372";
    public String url_photography="https://api.jsonbin.io/b/5a4865947835fe482d9cc153";
    public String url_physics="https://api.jsonbin.io/b/5a4865e3e01e8f485451c373";
    public String url_plagarism="https://api.jsonbin.io/b/5a4866667835fe482d9cc154";
    public String url_planning="https://api.jsonbin.io/b/5a4868c8e01e8f485451c375";
    public String url_poetry="https://api.jsonbin.io/b/5a48693fe01e8f485451c376";
    public String url_politician="https://api.jsonbin.io/b/5a48699be01e8f485451c377";
    public String url_politics="https://api.jsonbin.io/b/5a4869d67835fe482d9cc157";
    public String url_posessions="https://api.jsonbin.io/b/5a486a27163d58482c19d7dc";
    public String url_poverty="https://api.jsonbin.io/b/5a486a93664554485a29a417";
    public String url_power="https://api.jsonbin.io/b/5a486af2e01e8f485451c378";
    public String url_praise="https://api.jsonbin.io/b/5a486b43163d58482c19d7dd";
    public String url_prayer="https://api.jsonbin.io/b/5a486bc1664554485a29a419";
    public String url_prejudice="https://api.jsonbin.io/b/5a486bfe664554485a29a41a";
    public String url_pride="https://api.jsonbin.io/b/5a486c57163d58482c19d7df";
    public String url_promises="https://api.jsonbin.io/b/5a486ced664554485a29a41c";
    public String url_proverbs="https://api.jsonbin.io/b/5a486d48664554485a29a41d";
    public String url_questioning="https://api.jsonbin.io/b/5a486d48664554485a29a41d";
    public String url_quotations="https://api.jsonbin.io/b/5a486ed1e01e8f485451c379";
    public String url_reality="https://api.jsonbin.io/b/5a486f3e163d58482c19d7e1";
    public String url_reason="https://api.jsonbin.io/b/5a486fc7e01e8f485451c37a";
    public String url_relaxation="https://api.jsonbin.io/b/5a487028664554485a29a420";
    public String url_religion="https://api.jsonbin.io/b/5a48717a7835fe482d9cc15e";
    public String url_respect="https://api.jsonbin.io/b/5a4871d1163d58482c19d7e8";
    public String url_responsibility="https://api.jsonbin.io/b/5a48723ae01e8f485451c37c";
    public String url_revenge="https://api.jsonbin.io/b/5a4872b57835fe482d9cc15f";
    public String url_revolution="https://api.jsonbin.io/b/5a4873017835fe482d9cc160";
    public String url_risks="https://api.jsonbin.io/b/5a487380163d58482c19d7e9";
    public String url_rules="https://api.jsonbin.io/b/5a48766ee01e8f485451c380";
    public String url_sanity="https://api.jsonbin.io/b/5a4876d0664554485a29a425";
    public String url_science="https://api.jsonbin.io/b/5a48773e7835fe482d9cc163";
    public String url_secrets="https://api.jsonbin.io/b/5a4877a6664554485a29a426";
    public String url_security="https://api.jsonbin.io/b/5a4877fa664554485a29a427";
    public String url_selfishness="https://api.jsonbin.io/b/5a48783ae01e8f485451c381";
    public String url_services="https://api.jsonbin.io/b/5a4878c1664554485a29a428";
    public String url_silence="https://api.jsonbin.io/b/5a487a55e01e8f485451c382";
    public String url_simplicity="https://api.jsonbin.io/b/5a487f08e01e8f485451c385";
    public String url_sleep="https://api.jsonbin.io/b/5a4880b6163d58482c19d7f3";
    public String url_snow="https://api.jsonbin.io/b/5a4884ed163d58482c19d7f5";
    public String url_society="https://api.jsonbin.io/b/5a48869c163d58482c19d7f7";
    public String url_speech="https://api.jsonbin.io/b/5a488767e01e8f485451c389";
    public String url_sports="https://api.jsonbin.io/b/5a54c03a75f6c54daf7f71c1";
    public String url_spring="https://api.jsonbin.io/b/5a54c0b27cfd5a4dbc6b18cf";
    public String url_statistics="https://api.jsonbin.io/b/5a54c1767cfd5a4dbc6b18da";
    public String url_stupidity="https://api.jsonbin.io/b/5a59a339fa0fa33d7b63f0f0";
    public String url_success="https//api.jsonbin.io/b/5a59a3fba8fa173d86ae09e0";
    public String url_suffering="https://api.jsonbin.io/b/5a59a45c75f6c54daf7fb008";
    public String url_summer="https://api.jsonbin.io/b/5a59a4affa0fa33d7b63f106";
    public String url_superstition="https://api.jsonbin.io/b/5a59a4eba8fa173d86ae09f0";
    public String url_talent="https://api.jsonbin.io/b/5a59a584fa0fa33d7b63f115";
    public String url_taxes="https://api.jsonbin.io/b/5a59a832a8fa173d86ae0a1e";
    public String url_teaching="https://api.jsonbin.io/b/5a59a88f7cfd5a4dbc6b5754";
    public String url_technology="https://api.jsonbin.io/b/5a59aa9275f6c54daf7fb05a";
    public String url_telivision="https://api.jsonbin.io/b/5a59ab90fa0fa33d7b63f163";
    public String url_temptation="https://api.jsonbin.io/b/5a59ab90fa0fa33d7b63f163";
    public String url_thefuture="https://api.jsonbin.io/b/5a59ac5a7cfd5a4dbc6b578b";
    public String url_thepast="https://api.jsonbin.io/b/5a59ad08a8fa173d86ae0a5d";
    public String url_theworld="https://api.jsonbin.io/b/5a59ad3cfa0fa33d7b63f178";
    public String url_thoughts="https://api.jsonbin.io/b/5a59ad8afa0fa33d7b63f17c";
    public String url_time="https://api.jsonbin.io/b/5a59fd4bacbc7b5460be1108";
    public String url_travel="http://api.jsonbin.io/b/5a59fd8facbc7b5460be110d";
    public String url_trees="https://api.jsonbin.io/b/5a59fddd3b7c56545f89243a";
    public String url_trust="https://api.jsonbin.io/b/5a59fe363b7c56545f89243f";
    public String url_uncertainity="https://api.jsonbin.io/b/5a5a001aacbc7b5460be1130";
    public String url_understanding="https://api.jsonbin.io/b/5a5a00afe781585477888f2b";
    public String url_values="https://api.jsonbin.io/b/5a5a01bee781585477888f38";
    public String url_vices="https://api.jsonbin.io/b/5a5a020fe781585477888f3d";
    public String url_victory="https://api.jsonbin.io/b/5a5a02a0d233ba5478628193";
    public String url_violence="https://api.jsonbin.io/b/5a5a0328acbc7b5460be1158";
    public String url_wealth="https://api.jsonbin.io/b/5a5a0436e781585477888f5a";
    public String url_wisdom="https://api.jsonbin.io/b/5a5a057b3b7c56545f89249c";
    public String url_wishes="https://api.jsonbin.io/b/5a5a057b3b7c56545f89249c";
    public String url_work="https://api.jsonbin.io/b/5a5a0675acbc7b5460be1185";
    public String url_worries="https://api.jsonbin.io/b/5a5a06d03b7c56545f8924af";
    public String url_writings="https://api.jsonbin.io/b/5a5a0936e781585477888f98";
    public String url_youth="https://api.jsonbin.io/b/5a5a09c4d233ba54786281eb";




    private ArrayList<Quotes> quoteslist = new ArrayList<>();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Spinner mSpinner= (Spinner) findViewById(R.id.cat_spinner);
        ArrayAdapter<CharSequence> mCatArrayAdapter = ArrayAdapter.createFromResource(this,R.array.quote_cat,android.R.layout.simple_spinner_item);
        mCatArrayAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        mSpinner.setAdapter(mCatArrayAdapter);
        progressBar = (ProgressBar) findViewById(R.id.progerssview);
        recyclerView = (RecyclerView) findViewById(R.id.quote_recycler_view);

        mSpinner = (Spinner) findViewById(R.id.cat_spinner);
        mSpinner.setOnItemSelectedListener(this);
        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(getApplicationContext());
        recyclerView.setLayoutManager(mLayoutManager);


        Log.e("abc",""+quoteslist);

    }
    public void volleyArrayRequest(String url)
    { StringRequest stringRequest = new StringRequest(Request.Method.GET, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                progressBar.setVisibility(View.GONE);
                try {

                    JSONObject obj = new JSONObject(response);
                    JSONArray quotesarray = obj.getJSONArray("selection1");
                    for(int i=0;i<quotesarray.length();i++){
                        JSONObject quoteitem = quotesarray.getJSONObject(i);
                        String singlequote = quoteitem.getString("name");
                        Quotes quotes = new Quotes(singlequote);
                        quoteslist.add(quotes);
                        adapter1 = new RecyclerAdapter(MainActivity.this,quoteslist);
                        recyclerView.setAdapter(adapter1);




                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }

            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {

            }
        });
        AppSingleton.getInstance(MainActivity.this).addToRequestQueue(stringRequest,"ABC");
    }

    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {

        switch (i){
            case 0:volleyArrayRequest(url_argument);
                quoteslist.clear();
                break;
            case 1:volleyArrayRequest(url_advice);
                quoteslist.clear();
                break;
            case 2:volleyArrayRequest(url_america);
                quoteslist.clear();
                break;
            case 3:volleyArrayRequest(url_actions);
                quoteslist.clear();
                break;
            case 4:volleyArrayRequest(url_authority);
                quoteslist.clear();
                break;
            case 5:volleyArrayRequest(url_attitude);
                quoteslist.clear();
                break;
            case 6:volleyArrayRequest(url_autmn);
                quoteslist.clear();
                break;
            case 7:volleyArrayRequest(url_balance);
                quoteslist.clear();
                break;
            case 8:volleyArrayRequest(url_beauty);
                quoteslist.clear();
                break;
            case 9:volleyArrayRequest(url_belief);
                quoteslist.clear();
                break;
            case 10:volleyArrayRequest(url_birds);
                quoteslist.clear();
                break;
            case 11:volleyArrayRequest(url_body);
                quoteslist.clear();
                break;
            case 12:volleyArrayRequest(url_books);
                quoteslist.clear();
                break;
            case 13:volleyArrayRequest(url_boredom);
                quoteslist.clear();
                break;
            case 14:volleyArrayRequest(url_brain);
                quoteslist.clear();
                break;
            case 15:volleyArrayRequest(url_business);
                quoteslist.clear();
                break;
            case 16:volleyArrayRequest(url_camping);
                quoteslist.clear();
                break;
            case 17:volleyArrayRequest(url_cats);
                quoteslist.clear();
                break;
            case 18:volleyArrayRequest(url_chance);
                quoteslist.clear();
                break;
            case 19:volleyArrayRequest(url_change);
                quoteslist.clear();
                break;
            case 20:volleyArrayRequest(url_character);
                quoteslist.clear();
                break;
            case 21:volleyArrayRequest(url_christmas);
                quoteslist.clear();
                break;
            case 22:volleyArrayRequest(url_civilization);
                quoteslist.clear();
                break;
            case 23:volleyArrayRequest(url_cliche);
                quoteslist.clear();
                break;
            case 24:volleyArrayRequest(url_commonsense);
                quoteslist.clear();
                break;
            case 25:volleyArrayRequest(url_communication);
                quoteslist.clear();
                break;
            case 26:volleyArrayRequest(url_communism);
                quoteslist.clear();
                break;
            case 27:volleyArrayRequest(url_community);
                quoteslist.clear();
                break;
            case 28:volleyArrayRequest(url_compete);
                quoteslist.clear();
                break;
            case 29:volleyArrayRequest(url_computers);
                quoteslist.clear();
                break;
            case 30:volleyArrayRequest(url_conceit);
                quoteslist.clear();
                break;
            case 31:volleyArrayRequest(url_confidence);
                quoteslist.clear();
                break;
            case 32:volleyArrayRequest(url_conservative);
                quoteslist.clear();
                break;
            case 33:volleyArrayRequest(url_conversation);
                quoteslist.clear();break;
            case 34:volleyArrayRequest(url_courage);
                quoteslist.clear();break;
            case 35:volleyArrayRequest(url_coward);
                quoteslist.clear();break;
            case 36:volleyArrayRequest(url_creativity);
                quoteslist.clear();break;
            case 37:volleyArrayRequest(url_crime);
                quoteslist.clear();break;
            case 38:volleyArrayRequest(url_criticism);
                quoteslist.clear();break;
            case 39:volleyArrayRequest(url_curiosity);
                quoteslist.clear();break;
            case 40:volleyArrayRequest(url_cynicism);
                quoteslist.clear();break;
            case 41:volleyArrayRequest(url_dance);
                quoteslist.clear();break;
            case 42:volleyArrayRequest(url_death);
                quoteslist.clear();break;
            case 43:volleyArrayRequest(url_decision);
                quoteslist.clear();break;
            case 44:volleyArrayRequest(url_defeat);
                quoteslist.clear();break;
            case 45:volleyArrayRequest(url_democracy);
                quoteslist.clear();break;
            case 46:volleyArrayRequest(url_design);
                quoteslist.clear();break;
            case 47:volleyArrayRequest(url_destiny);
                quoteslist.clear();break;
            case 48:volleyArrayRequest(url_differences);
                quoteslist.clear();
                break;
            case 49:volleyArrayRequest(url_dignity);
                quoteslist.clear();break;
            case 50:volleyArrayRequest(url_discovery);
                quoteslist.clear();break;
            case 51:volleyArrayRequest(url_dogs);
                quoteslist.clear();break;
            case 52:volleyArrayRequest(url_doubt);
                quoteslist.clear();break;
            case 53:volleyArrayRequest(url_dream);
                quoteslist.clear();break;
            case 54:volleyArrayRequest(url_duty);
                quoteslist.clear();break;
            case 55:volleyArrayRequest(url_economics);
                quoteslist.clear();break;
            case 56:volleyArrayRequest(url_education);
                quoteslist.clear();break;
            case 57:volleyArrayRequest(url_enemies);
                quoteslist.clear();break;
            case 58:volleyArrayRequest(url_energy);
                quoteslist.clear();break;
            case 59:volleyArrayRequest(url_england);
                quoteslist.clear();break;
            case 60:volleyArrayRequest(url_english);
                quoteslist.clear();break;
            case 61:volleyArrayRequest(url_environment);
                quoteslist.clear();break;
            case 62:volleyArrayRequest(url_equality);
                quoteslist.clear();break;
            case 63:volleyArrayRequest(url_etiquette);
                quoteslist.clear();break;
            case 64:volleyArrayRequest(url_evil);
                quoteslist.clear();break;
            case 65:volleyArrayRequest(url_excel);
                quoteslist.clear();break;
            case 66:volleyArrayRequest(url_exercise);
                quoteslist.clear();break;
            case 67:volleyArrayRequest(url_experience);
                quoteslist.clear();break;
            case 68:volleyArrayRequest(url_experts);
                quoteslist.clear();break;
            case 69:volleyArrayRequest(url_exploration);
                quoteslist.clear();break;
            case 70:volleyArrayRequest(url_facts);
                quoteslist.clear();break;
            case 71:volleyArrayRequest(url_failure);
                quoteslist.clear();break;
            case 72:volleyArrayRequest(url_faith);
                quoteslist.clear();break;
            case 73:volleyArrayRequest(url_fame);
                quoteslist.clear();break;
            case 74:volleyArrayRequest(url_family);
                quoteslist.clear();break;
            case 75:volleyArrayRequest(url_fashion);
                quoteslist.clear();break;
            case 76:volleyArrayRequest(url_fate);
                quoteslist.clear();break;
            case 77:volleyArrayRequest(url_fear);
                quoteslist.clear();break;
            case 78:volleyArrayRequest(url_flowers);
                quoteslist.clear();break;
            case 79:volleyArrayRequest(url_food);
                quoteslist.clear();break;
            case 80:volleyArrayRequest(url_forgiveness);
                quoteslist.clear();break;
            case 81:volleyArrayRequest(url_fortune);
                quoteslist.clear();break;
            case 82:volleyArrayRequest(url_freedom);
                quoteslist.clear();break;
            case 83:volleyArrayRequest(url_friends);
                quoteslist.clear();break;
            case 84:volleyArrayRequest(url_genius);
                quoteslist.clear();break;
            case 85:volleyArrayRequest(url_giving);
                quoteslist.clear();break;
            case 86:volleyArrayRequest(url_goals);
                quoteslist.clear();break;
            case 87:volleyArrayRequest(url_god);
                quoteslist.clear();
                break;
            case 88:volleyArrayRequest(url_golf);
                quoteslist.clear();break;
            case 89:volleyArrayRequest(url_gossip);
                quoteslist.clear();break;
            case 90:volleyArrayRequest(url_government);
                quoteslist.clear();break;
            case 91:volleyArrayRequest(url_gratitude);
                quoteslist.clear();break;
            case 92:volleyArrayRequest(url_greatness);
                quoteslist.clear();break;
            case 93:volleyArrayRequest(url_greed);
                quoteslist.clear();break;
            case 94:volleyArrayRequest(url_grief);
                quoteslist.clear();break;
            case 95:volleyArrayRequest(url_guilt);
                quoteslist.clear();break;
            case 96:volleyArrayRequest(url_habits);
                quoteslist.clear();break;
            case 97:volleyArrayRequest(url_happiness);
                quoteslist.clear();break;
            case 98:volleyArrayRequest(url_hate);
                quoteslist.clear();break;
            case 99:volleyArrayRequest(url_hatred);
                quoteslist.clear();break;
            case 100:volleyArrayRequest(url_health);
                quoteslist.clear();break;
            case 101:volleyArrayRequest(url_hero);
                quoteslist.clear();break;
            case 102:volleyArrayRequest(url_history);
                quoteslist.clear();break;
            case 103:volleyArrayRequest(url_hollywood);
                quoteslist.clear();break;
            case 104:volleyArrayRequest(url_home);
                quoteslist.clear();break;
            case 105:volleyArrayRequest(url_honesty);
                quoteslist.clear();break;
            case 106:volleyArrayRequest(url_honor);
                quoteslist.clear();break;
            case 107:volleyArrayRequest(url_hope);
                quoteslist.clear();break;
            case 108:volleyArrayRequest(url_humility);
                quoteslist.clear();break;
            case 109:volleyArrayRequest(url_humour);
                quoteslist.clear();break;
            case 110:volleyArrayRequest(url_idealism);
                quoteslist.clear();break;
            case 111:volleyArrayRequest(url_ideas);
                quoteslist.clear();break;
            case 112:volleyArrayRequest(url_ignorance);
                quoteslist.clear();break;
            case 113:volleyArrayRequest(url_imagination);
                quoteslist.clear();break;
            case 114:volleyArrayRequest(url_immoratality);
                quoteslist.clear();break;
            case 115:volleyArrayRequest(url_inspiration);
                quoteslist.clear();break;
            case 116:volleyArrayRequest(url_instinct);
                quoteslist.clear();break;
            case 117:volleyArrayRequest(url_integrity);
                quoteslist.clear();break;
            case 118:volleyArrayRequest(url_intelligence);
                quoteslist.clear();break;
            case 119:volleyArrayRequest(url_internet);
                quoteslist.clear();break;
            case 120:volleyArrayRequest(url_invention);
                quoteslist.clear();break;
            case 121:volleyArrayRequest(url_jealousy);
                quoteslist.clear();break;
            case 122:volleyArrayRequest(url_journalism);
                quoteslist.clear();break;
            case 123:volleyArrayRequest(url_joy);
                quoteslist.clear();break;
            case 124:volleyArrayRequest(url_justice);
                quoteslist.clear();break;
            case 125:volleyArrayRequest(url_kindness);
                quoteslist.clear();break;
            case 126:volleyArrayRequest(url_knowledge);
                quoteslist.clear();break;
            case 127:volleyArrayRequest(url_language);
                quoteslist.clear();break;
            case 128:volleyArrayRequest(url_laughter);
                quoteslist.clear();break;
            case 129:volleyArrayRequest(url_laws);
                quoteslist.clear();
                break;
            case 130:volleyArrayRequest(url_laziness);
                quoteslist.clear();break;
            case 131:volleyArrayRequest(url_leadership);
                quoteslist.clear();break;
            case 132:volleyArrayRequest(url_learning);
                quoteslist.clear();break;
            case 133:volleyArrayRequest(url_legacy);
                quoteslist.clear();break;
            case 134:volleyArrayRequest(url_liberals);
                quoteslist.clear();break;
            case 135:volleyArrayRequest(url_lies);
                quoteslist.clear();break;
            case 136:volleyArrayRequest(url_life);
                quoteslist.clear();break;
            case 137:volleyArrayRequest(url_light);
                quoteslist.clear();break;
            case 138:volleyArrayRequest(url_listening);
                quoteslist.clear();break;
            case 139:volleyArrayRequest(url_lonliness);
                quoteslist.clear();break;
            case 140:volleyArrayRequest(url_love);
                quoteslist.clear();break;
            case 141:volleyArrayRequest(url_luck);
                quoteslist.clear();break;
            case 142:volleyArrayRequest(url_magic);
                quoteslist.clear();break;
            case 143:volleyArrayRequest(url_mankind);
                quoteslist.clear();break;
            case 144:volleyArrayRequest(url_marriage);
                quoteslist.clear();break;
            case 145:volleyArrayRequest(url_mathematics);
                quoteslist.clear();break;
            case 146:volleyArrayRequest(url_medicine);
                quoteslist.clear();break;
            case 147:volleyArrayRequest(url_memory);
                quoteslist.clear();break;
            case 148:volleyArrayRequest(url_menandwoman);
                quoteslist.clear();break;
            case 149:volleyArrayRequest(url_mercy);
                quoteslist.clear();break;
            case 150:volleyArrayRequest(url_mistakes);
                quoteslist.clear();break;
            case 151:volleyArrayRequest(url_money);
                quoteslist.clear();break;
            case 152:volleyArrayRequest(url_morality);
                quoteslist.clear();break;
            case 153:volleyArrayRequest(url_morning);
                quoteslist.clear();break;
            case 154:volleyArrayRequest(url_music);
                quoteslist.clear();break;
            case 155:volleyArrayRequest(url_nature);
                quoteslist.clear();break;
            case 156:volleyArrayRequest(url_necessity);
                quoteslist.clear();break;
            case 157:volleyArrayRequest(url_night);
                quoteslist.clear();
                break;
            case 158:volleyArrayRequest(url_nobility);
                quoteslist.clear();break;
            case 159:volleyArrayRequest(url_opinions);
                quoteslist.clear();break;
            case 160:volleyArrayRequest(url_opportunity);
                quoteslist.clear();
                break;
            case 161:volleyArrayRequest(url_optimism);
                quoteslist.clear();break;
            case 162:volleyArrayRequest(url_painting);
                quoteslist.clear();break;
            case 163:volleyArrayRequest(url_parents);
                quoteslist.clear();break;
            case 164:volleyArrayRequest(url_passion);
                quoteslist.clear();break;
            case 165:volleyArrayRequest(url_patience);
                quoteslist.clear();break;
            case 166:volleyArrayRequest(url_patiotism);
                quoteslist.clear();break;
            case 167:volleyArrayRequest(url_peace);
                quoteslist.clear();break;
            case 168:volleyArrayRequest(url_perfection);
                quoteslist.clear();break;
            case 169:volleyArrayRequest(url_preserverance);
                quoteslist.clear();break;
            case 170:volleyArrayRequest(url_philosophy);
                quoteslist.clear();break;
            case 171:volleyArrayRequest(url_photography);
                quoteslist.clear();break;
            case 172:volleyArrayRequest(url_physics);
                quoteslist.clear();break;
            case 173:volleyArrayRequest(url_plagarism);
                quoteslist.clear();break;
            case 174:volleyArrayRequest(url_planning);
                quoteslist.clear();
                break;
            case 175:volleyArrayRequest(url_poetry);
                quoteslist.clear();break;
            case 176:volleyArrayRequest(url_politician);
                quoteslist.clear();break;
            case 177:volleyArrayRequest(url_politics);
                quoteslist.clear();break;
            case 178:volleyArrayRequest(url_posessions);
                quoteslist.clear();break;
            case 179:volleyArrayRequest(url_poverty);
                quoteslist.clear();break;
            case 180:volleyArrayRequest(url_power);
                quoteslist.clear();break;
            case 181:volleyArrayRequest(url_praise);
                quoteslist.clear();break;
            case 182:volleyArrayRequest(url_prayer);
                quoteslist.clear();break;
            case 183:volleyArrayRequest(url_prejudice);
                quoteslist.clear();break;
            case 184:volleyArrayRequest(url_pride);
                quoteslist.clear();break;
            case 185:volleyArrayRequest(url_promises);
                quoteslist.clear();break;
            case 186:volleyArrayRequest(url_proverbs);
                quoteslist.clear();break;
            case 187:volleyArrayRequest(url_questioning);
                quoteslist.clear();break;
            case 188:volleyArrayRequest(url_quotations);
                quoteslist.clear();break;
            case 189:volleyArrayRequest(url_reality);
                quoteslist.clear();break;
            case 190:volleyArrayRequest(url_reason);
                quoteslist.clear();break;
            case 191:volleyArrayRequest(url_relaxation);
                quoteslist.clear();break;
            case 192:volleyArrayRequest(url_religion);
                quoteslist.clear();break;
            case 193:volleyArrayRequest(url_respect);
                quoteslist.clear();
                break;
            case 194:volleyArrayRequest(url_responsibility);
                quoteslist.clear();
                break;
            case 195:volleyArrayRequest(url_revenge);
                quoteslist.clear();break;
            case 196:volleyArrayRequest(url_revolution);
                quoteslist.clear();break;
            case 197:volleyArrayRequest(url_risks);
                quoteslist.clear();break;
            case 198:volleyArrayRequest(url_rules);
                quoteslist.clear();break;
            case 199:volleyArrayRequest(url_sanity);
                quoteslist.clear();break;
            case 200:volleyArrayRequest(url_science);
                quoteslist.clear();break;
            case 201:volleyArrayRequest(url_secrets);
                quoteslist.clear();break;
            case 202:volleyArrayRequest(url_security);
                quoteslist.clear();break;
            case 203:volleyArrayRequest(url_selfishness);
                quoteslist.clear();break;
            case 204:volleyArrayRequest(url_services);
                quoteslist.clear();
                break;
            case 205:volleyArrayRequest(url_silence);
                quoteslist.clear();break;
            case 206:volleyArrayRequest(url_simplicity);
                quoteslist.clear();break;
            case 207:volleyArrayRequest(url_sleep);
                quoteslist.clear();break;
            case 208:volleyArrayRequest(url_snow);
                quoteslist.clear();break;
            case 209:volleyArrayRequest(url_society);
                quoteslist.clear();break;
            case 210:volleyArrayRequest(url_speech);
                quoteslist.clear();break;
            case 211:volleyArrayRequest(url_sports);
                quoteslist.clear();break;
            case 212:volleyArrayRequest(url_spring);
                quoteslist.clear();break;
            case 213:volleyArrayRequest(url_statistics);
                quoteslist.clear();break;
            case 214:volleyArrayRequest(url_stupidity);
                quoteslist.clear();break;
            case 215:volleyArrayRequest(url_success);
                quoteslist.clear();break;
            case 216:volleyArrayRequest(url_suffering);
                quoteslist.clear();break;
            case 217:volleyArrayRequest(url_summer);
                quoteslist.clear();break;
            case 218:volleyArrayRequest(url_superstition);
                quoteslist.clear();break;
            case 219:volleyArrayRequest(url_talent);
                quoteslist.clear();break;
            case 220:volleyArrayRequest(url_taxes);
                quoteslist.clear();break;
            case 221:volleyArrayRequest(url_teaching);
                quoteslist.clear();break;
            case 222:volleyArrayRequest(url_technology);
                quoteslist.clear();break;
            case 223:volleyArrayRequest(url_telivision);
                quoteslist.clear();break;
            case 224:volleyArrayRequest(url_temptation);
                quoteslist.clear();break;
            case 225:volleyArrayRequest(url_thefuture);
                quoteslist.clear();break;
            case 226:volleyArrayRequest(url_thepast);
                quoteslist.clear();break;
            case 227:volleyArrayRequest(url_theworld);
                quoteslist.clear();break;
            case 228:volleyArrayRequest(url_thoughts);
                quoteslist.clear();break;
            case 229:volleyArrayRequest(url_time);
                quoteslist.clear();break;
            case 230:volleyArrayRequest(url_travel);
                quoteslist.clear();break;
            case 231:volleyArrayRequest(url_trees);
                quoteslist.clear();break;
            case 232:volleyArrayRequest(url_trust);
                quoteslist.clear();break;
            case 233:volleyArrayRequest(url_uncertainity);
                quoteslist.clear();break;
            case 234:volleyArrayRequest(url_understanding);
                quoteslist.clear();break;
            case 235:volleyArrayRequest(url_values);
                quoteslist.clear();break;
            case 236:volleyArrayRequest(url_vices);
                quoteslist.clear();break;
            case 237:volleyArrayRequest(url_victory);
                quoteslist.clear();break;
            case 238:volleyArrayRequest(url_violence);
                quoteslist.clear();break;
            case 239:volleyArrayRequest(url_wealth);
                quoteslist.clear();break;
            case 240:volleyArrayRequest(url_wisdom);
                quoteslist.clear();break;
            case 241:volleyArrayRequest(url_wishes);
                quoteslist.clear();break;
            case 242:volleyArrayRequest(url_work);
                quoteslist.clear();break;
            case 243:volleyArrayRequest(url_worries);
                quoteslist.clear();break;
            case 244:volleyArrayRequest(url_writings);
                quoteslist.clear();break;
            case 245:volleyArrayRequest(url_youth);
                quoteslist.clear();break;

        }
    }

    @Override
    public void onNothingSelected(AdapterView<?> adapterView) {
        volleyArrayRequest(url_authority);
    }



}
